require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MeetingMinutesEmailsController do

  # This should return the minimal set of attributes required to create a valid
  # MeetingMinutesEmail. As you add validations to MeetingMinutesEmail, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MeetingMinutesEmailsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all meeting_minutes_emails as @meeting_minutes_emails" do
      meeting_minutes_email = MeetingMinutesEmail.create! valid_attributes
      get :index, {}, valid_session
      assigns(:meeting_minutes_emails).should eq([meeting_minutes_email])
    end
  end

  describe "GET show" do
    it "assigns the requested meeting_minutes_email as @meeting_minutes_email" do
      meeting_minutes_email = MeetingMinutesEmail.create! valid_attributes
      get :show, {:id => meeting_minutes_email.to_param}, valid_session
      assigns(:meeting_minutes_email).should eq(meeting_minutes_email)
    end
  end

  describe "GET new" do
    it "assigns a new meeting_minutes_email as @meeting_minutes_email" do
      get :new, {}, valid_session
      assigns(:meeting_minutes_email).should be_a_new(MeetingMinutesEmail)
    end
  end

  describe "GET edit" do
    it "assigns the requested meeting_minutes_email as @meeting_minutes_email" do
      meeting_minutes_email = MeetingMinutesEmail.create! valid_attributes
      get :edit, {:id => meeting_minutes_email.to_param}, valid_session
      assigns(:meeting_minutes_email).should eq(meeting_minutes_email)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MeetingMinutesEmail" do
        expect {
          post :create, {:meeting_minutes_email => valid_attributes}, valid_session
        }.to change(MeetingMinutesEmail, :count).by(1)
      end

      it "assigns a newly created meeting_minutes_email as @meeting_minutes_email" do
        post :create, {:meeting_minutes_email => valid_attributes}, valid_session
        assigns(:meeting_minutes_email).should be_a(MeetingMinutesEmail)
        assigns(:meeting_minutes_email).should be_persisted
      end

      it "redirects to the created meeting_minutes_email" do
        post :create, {:meeting_minutes_email => valid_attributes}, valid_session
        response.should redirect_to(MeetingMinutesEmail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved meeting_minutes_email as @meeting_minutes_email" do
        # Trigger the behavior that occurs when invalid params are submitted
        MeetingMinutesEmail.any_instance.stub(:save).and_return(false)
        post :create, {:meeting_minutes_email => {}}, valid_session
        assigns(:meeting_minutes_email).should be_a_new(MeetingMinutesEmail)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MeetingMinutesEmail.any_instance.stub(:save).and_return(false)
        post :create, {:meeting_minutes_email => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested meeting_minutes_email" do
        meeting_minutes_email = MeetingMinutesEmail.create! valid_attributes
        # Assuming there are no other meeting_minutes_emails in the database, this
        # specifies that the MeetingMinutesEmail created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MeetingMinutesEmail.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => meeting_minutes_email.to_param, :meeting_minutes_email => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested meeting_minutes_email as @meeting_minutes_email" do
        meeting_minutes_email = MeetingMinutesEmail.create! valid_attributes
        put :update, {:id => meeting_minutes_email.to_param, :meeting_minutes_email => valid_attributes}, valid_session
        assigns(:meeting_minutes_email).should eq(meeting_minutes_email)
      end

      it "redirects to the meeting_minutes_email" do
        meeting_minutes_email = MeetingMinutesEmail.create! valid_attributes
        put :update, {:id => meeting_minutes_email.to_param, :meeting_minutes_email => valid_attributes}, valid_session
        response.should redirect_to(meeting_minutes_email)
      end
    end

    describe "with invalid params" do
      it "assigns the meeting_minutes_email as @meeting_minutes_email" do
        meeting_minutes_email = MeetingMinutesEmail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MeetingMinutesEmail.any_instance.stub(:save).and_return(false)
        put :update, {:id => meeting_minutes_email.to_param, :meeting_minutes_email => {}}, valid_session
        assigns(:meeting_minutes_email).should eq(meeting_minutes_email)
      end

      it "re-renders the 'edit' template" do
        meeting_minutes_email = MeetingMinutesEmail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MeetingMinutesEmail.any_instance.stub(:save).and_return(false)
        put :update, {:id => meeting_minutes_email.to_param, :meeting_minutes_email => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested meeting_minutes_email" do
      meeting_minutes_email = MeetingMinutesEmail.create! valid_attributes
      expect {
        delete :destroy, {:id => meeting_minutes_email.to_param}, valid_session
      }.to change(MeetingMinutesEmail, :count).by(-1)
    end

    it "redirects to the meeting_minutes_emails list" do
      meeting_minutes_email = MeetingMinutesEmail.create! valid_attributes
      delete :destroy, {:id => meeting_minutes_email.to_param}, valid_session
      response.should redirect_to(meeting_minutes_emails_url)
    end
  end

end
