require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PrelaunchesController do

  # This should return the minimal set of attributes required to create a valid
  # Prelaunch. As you add validations to Prelaunch, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PrelaunchesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all prelaunches as @prelaunches" do
      prelaunch = Prelaunch.create! valid_attributes
      get :index, {}, valid_session
      assigns(:prelaunches).should eq([prelaunch])
    end
  end

  describe "GET show" do
    it "assigns the requested prelaunch as @prelaunch" do
      prelaunch = Prelaunch.create! valid_attributes
      get :show, {:id => prelaunch.to_param}, valid_session
      assigns(:prelaunch).should eq(prelaunch)
    end
  end

  describe "GET new" do
    it "assigns a new prelaunch as @prelaunch" do
      get :new, {}, valid_session
      assigns(:prelaunch).should be_a_new(Prelaunch)
    end
  end

  describe "GET edit" do
    it "assigns the requested prelaunch as @prelaunch" do
      prelaunch = Prelaunch.create! valid_attributes
      get :edit, {:id => prelaunch.to_param}, valid_session
      assigns(:prelaunch).should eq(prelaunch)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Prelaunch" do
        expect {
          post :create, {:prelaunch => valid_attributes}, valid_session
        }.to change(Prelaunch, :count).by(1)
      end

      it "assigns a newly created prelaunch as @prelaunch" do
        post :create, {:prelaunch => valid_attributes}, valid_session
        assigns(:prelaunch).should be_a(Prelaunch)
        assigns(:prelaunch).should be_persisted
      end

      it "redirects to the created prelaunch" do
        post :create, {:prelaunch => valid_attributes}, valid_session
        response.should redirect_to(Prelaunch.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved prelaunch as @prelaunch" do
        # Trigger the behavior that occurs when invalid params are submitted
        Prelaunch.any_instance.stub(:save).and_return(false)
        post :create, {:prelaunch => {}}, valid_session
        assigns(:prelaunch).should be_a_new(Prelaunch)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Prelaunch.any_instance.stub(:save).and_return(false)
        post :create, {:prelaunch => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested prelaunch" do
        prelaunch = Prelaunch.create! valid_attributes
        # Assuming there are no other prelaunches in the database, this
        # specifies that the Prelaunch created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Prelaunch.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => prelaunch.to_param, :prelaunch => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested prelaunch as @prelaunch" do
        prelaunch = Prelaunch.create! valid_attributes
        put :update, {:id => prelaunch.to_param, :prelaunch => valid_attributes}, valid_session
        assigns(:prelaunch).should eq(prelaunch)
      end

      it "redirects to the prelaunch" do
        prelaunch = Prelaunch.create! valid_attributes
        put :update, {:id => prelaunch.to_param, :prelaunch => valid_attributes}, valid_session
        response.should redirect_to(prelaunch)
      end
    end

    describe "with invalid params" do
      it "assigns the prelaunch as @prelaunch" do
        prelaunch = Prelaunch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Prelaunch.any_instance.stub(:save).and_return(false)
        put :update, {:id => prelaunch.to_param, :prelaunch => {}}, valid_session
        assigns(:prelaunch).should eq(prelaunch)
      end

      it "re-renders the 'edit' template" do
        prelaunch = Prelaunch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Prelaunch.any_instance.stub(:save).and_return(false)
        put :update, {:id => prelaunch.to_param, :prelaunch => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested prelaunch" do
      prelaunch = Prelaunch.create! valid_attributes
      expect {
        delete :destroy, {:id => prelaunch.to_param}, valid_session
      }.to change(Prelaunch, :count).by(-1)
    end

    it "redirects to the prelaunches list" do
      prelaunch = Prelaunch.create! valid_attributes
      delete :destroy, {:id => prelaunch.to_param}, valid_session
      response.should redirect_to(prelaunches_url)
    end
  end

end
